Create table itunes_raw_2(
Provider varchar(10),
Provider_country varchar(5),
SKU varchar(),
Developer varchar(200),
Title varchar(200),
Version varchar(10),
Product_types varchar(20),
Units int,
Developer_proceeds decimal,
Begin_date varchar(20),
end_date varchar(20),
Customer_currency varchar(5),
Country_code varchar(5),
Country_proceeds varchar(5),
Apple_id varchar(40),
customer_price decimal,
Promo_code varchar(20),
Parent_id int,
Subscription varchar(20),
Period varchar(20),
Catagory varchar(15),
CMB varchar(10),
Device varchar(10),
Supported_platforms varchar(15)
);